template:
  - binary_sensor:
      - name: "EDC Running"
        unique_id: edc_running
        state: "off"
input_text:
  edc_script_duration:
    name: EDC Script Duration
    icon: mdi:timelapse
  edc_script_status:
    name: EDC Script Status
    icon: mdi:list-status
  edc_script_parameters:
    name: EDC Script Parameters
    icon: mdi:code-brackets
  edc_version:
    name: EDC Version
    icon: mdi:check-decagram
  edc_producer_eans:
    name: EDC Producer EANs
    icon: mdi:list-status
  edc_consumer_eans:
    name: EDC Consumer EANs
    icon: mdi:list-status


script:
  # script to load default data
  edc_import_default_interval:
    alias: EDC Import last month and current one
    sequence:
      - event: edc_import
        event_data: {}
    mode: single
    icon: "mdi:calendar-start-outline"
  edc_import_current_month:
    alias: EDC Import current month
    sequence:
      - event: edc_import_month
        event_data: {}
    mode: single
    icon: "mdi:calendar-start-outline"
  edc_import_custom_month:
    alias: EDC Import Custom Month/Year
    description: Import EDC data for a specific month and year
    fields:
      month:
        name: Month
        description: Month to import (1-12)
        required: true
        example: "1"
        selector:
          number:
            min: 1
            max: 12
            mode: box
      year:
        name: Year
        description: Year to import
        required: true
        example: "2026"
        selector:
          number:
            min: 2020
            max: 9999
            mode: box
    sequence:
      - event: edc_import_month
        event_data:
          month: "{{ month }}"
          year: "{{ year }}"
    mode: single
    icon: "mdi:calendar-edit"
  edc_import_daily:
    alias: EDC Import daily data
    sequence:
      - event: edc_import_daily
        event_data: {}
    mode: single
    icon: "mdi:calendar-start-outline"

homeassistant:
  # customization of elements, setting name, icons etc.
  customize:
    input_text.edc_script_duration:
      friendly_name: EDC Script Duration
    input_text.edc_script_status:
      friendly_name: EDC Script Status
    input_text.edc_script_parameters:
      friendly_name: EDC Script Parameters
    edc_version:
      friendly_name: EDC Version
    edc_producer_eans:
      friendly_name: EDC Producer EANs
    edc_consumer_eans:
      friendly_name: EDC Consumer EANs
